name: Publish

on:
  pull_request:
    branches:
    - main
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  publish:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'releases/')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: 'https://npm.pkg.github.com'

    - run: yarn --frozen-lockfile

    - uses: ./.github/actions/release-meta
      id: release-meta

    - name: Create GitHub Release
      uses: actions/github-script@v4
      with:
        script: |
          github.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: process.env.RELEASE_TAG,
            tag_name: process.env.RELEASE_TAG,
            body: process.env.RELEASE_NOTE,
            prerelease: !/v\d+\.\d+\.\d+$/.test(process.env.RELEASE_TAG),
            target_commitish: context.sha,
          })
      env:
        RELEASE_NOTE: ${{ steps.release-meta.outputs.note }}
        RELEASE_TAG: ${{ steps.release-meta.outputs.tag }}

    - name: Publish to npm
      run: |
        yarn lerna publish from-package --yes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment to PR
      uses: actions/github-script@v4
      with:
        script: |
          const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/releases/tag/${process.env.RELEASE_TAG}`
          github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `[${process.env.RELEASE_TAG}](${url}) is released 🚀`,
          })
      env:
        RELEASE_TAG: ${{ steps.release-meta.outputs.tag }}
