name: Release PR

on:
  pull_request:
    branches:
    - 'releases/**'
    types: [opened, synchronize]

permissions:
  pull-request: write

jobs:
  release-note:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn --frozen-lockfile
    - name: Generate CHANGELOG
      run: |
        version=$(node --print 'require("./lerna.json").version')
        echo "RELEASE_VERSION=${version}" >> $GITHUB_ENV
        echo "RELEASE_TAG=v${version}" >> $GITHUB_ENV
        echo "RELEASE_NOTE=$(yarn -s lerna-changelog --next-version-from-metadata)" >> $GITHUB_ENV
      env:
        GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
    - name: Update PR body
      uses: actions/github-script@v4
      with:
        script: |
          github.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            title: process.env.TAG,
            body: process.env.RELEASE_NOTE,
          })
