name: Release PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  release-note:
    if: startswith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn --frozen-lockfile

    - uses: ./.github/actions/release-meta
      id: release-meta

    - name: Update PR body
      uses: actions/github-script@v4
      with:
        script: |
          github.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            title: `Release ${process.env.RELEASE_TAG}`,
            body: process.env.RELEASE_NOTE,
          })
      env:
        RELEASE_NOTE: ${{ steps.release-meta.outputs.note }}
        RELEASE_TAG: ${{ steps.release-meta.outputs.tag }}

    - name: Setup git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update CHANGELOG.md
      run: |
        mkdir -p tmp
        echo "${RELEASE_NOTE}" > tmp/CHANGELOG.head.md
        git show ${{ github.base_ref }}:./CHANGELOG.md > tmp/CHANGELOG.base.md
        cat -s tmp/CHANGELOG.head.md tmp/CHANGELOG.base.md > CHANGELOG.md

        git add CHANGELOG.md
        git commit -m "Update CHANGELOG for ${RELEASE_TAG}"
        git push
      env:
        RELEASE_TAG: ${{ steps.release-meta.outputs.tag }}
        RELEASE_NOTE: ${{ steps.release-meta.outputs.note }}
