name: Release PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  release-note:
    if: startswith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn --frozen-lockfile
    - name: Generate Release note
      run: |
        version=$(node --print 'require("./lerna.json").version')
        echo $version
        yarn -s lerna-changelog --next-version-from-metadata
        note=$(yarn -s lerna-changelog --next-version-from-metadata)
        echo $note
        echo "::set-output name=version::${version}"
        echo "::set-output name=tag::v${version}"
        echo "::set-output name=note::${note//$'\n'/\\n}"
      env:
        GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
      id: release-meta
    - name: Update PR body
      uses: actions/github-script@v4
      with:
        script: |
          github.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            title: process.env.RELEASE_TAG,
            body: process.env.RELEASE_NOTE,
          })
      env:
        RELEASE_NOTE: ${{ steps.release-meta.outputs.note }}
        RELEASE_TAG: ${{ steps.release-meta.outputs.tag }}
